### ISSUE TITLE
Feature #1: User can login to an account

### ISSUE THREAD

**Issue by randygerada** [randygerada/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can can "login" and view the main page of application

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a pseudo login to allow user click a button to randomly receive an item from API.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-15 at 10 32 07 AM](https://user-images.githubusercontent.com/113477527/201999029-106c8661-e834-488e-82d5-ecdf40aadde1.png)
![Screenshot 2022-11-15 at 11 27 48 AM](https://user-images.githubusercontent.com/113477527/202581917-acde2726-2590-4322-a695-b46d85487415.png)
![Screenshot 2022-11-15 at 11 28 05 AM](https://user-images.githubusercontent.com/113477527/202582037-6587fd45-4c83-45f2-b1b9-210d360fa4fc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Create a pseudo login form. 
- [ ] inputs for form must be 'required.'
- [ ] Listen for " 'clicks' " hide login-page container.
- [ ] Listen for " 'clicks' " for modal.
- [ ] Define a function name 'knifeList' that uses XMLHttpRequest to request to a public api
   - [ ] within the code block, define a variable and  use the new XMLHttpRequest to create a new XHR object.
   - [ ] use open method to set request method and URL
   - [ ] use the resposneType to automatically parse to JSON
   - [ ] use addEventListener method to execute the function when response is eventually loaded
 - [ ] define a function that will randomly pick from the API.
 - [ ] query select your div[ ' api ' ] to later append the children from DOM Creation. 
 - [ ] use DOM creation within 'knifeList' and append each ('img') and ('h2') 
 - [ ] Append each child the div['api'].
 - [ ] Target your 'diffuse' button to display modal.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
